### ISSUE TITLE
build error when running the ILMerge for IncreasedMeterLimit

### ISSUE THREAD

**Issue by creatrope** [Berkays/OniMods#1]
Hi, i'm getting this ILMerge error in trying to build your repository. I've tried VS 2019 and VS2022.  ILMerge appears installed and working in the correct directory listed.  The Plib.dll and IncreasedMeterLimit.dll appear to be built and in the correct place.

1>  An exception occurred during merging:
1>  Unable to cast object of type 'System.Compiler.Class' to type 'System.Compiler.DelegateNode'.
1>     at System.Compiler.SystemTypes.Initialize(Boolean doNotLockFile, Boolean getDebugInfo, PostAssemblyLoadProcessor postAssemblyLoad)
1>     at System.Compiler.TargetPlatform.ResetCci(String platformAssembliesLocation, Version targetVersion, Boolean doNotLockFile, Boolean getDebugInfo, PostAssemblyLoadProcessor postAssemblyLoad)
1>     at ILMerging.ILMerge.Merge()
1>     at ILMerging.ILMerge.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5578,5): error MSB3073: The command ""C:\Users\hb\source\repos\ONI-mods-berkay\packages\ILMerge.3.0.41\build\..\tools\net452\ILMerge.exe" /ndebug  /out:IncreasedMeterLimitMerged.dll IncreasedMeterLimit.dll PLib.dll /targetplatform:v4,"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5578,5): error MSB3073: " exited with code 1.

**Comment by Berkays** [comment]
Seems to be a problem with the $(MSBuildToolsPath) variable not setting according to project's target framework. You can manually run the command `"OniMods\packages\ILMerge.3.0.41\tools\net452\ILMerge.exe /ndebug /out:IncreasedMeterLimit.dll IncreasedMeterLimit.dll PLib.dll /targetplatform:v4,"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1"`

Change the last .NETFramework path according to your sdk install location.

I might switch to a better ilmerger library later on.
