### ISSUE TITLE
Feature Request: Hysteresis Storage: Add Fish Feeder

### ISSUE THREAD

**Issue by patrioticparadox** [Berkays/OniMods#3]
The Fish Feeder should have hysteresis like the Critter Feeder does.

**Comment by Berkays** [comment]
Fish feeder is tricky because it has two storages. One for main tank and one for fish feeding arm. This prevents hysteresis to be triggered most of the time since top storage immediately feeds the bottom one. I may have to add an exception to add this feature but I'll look into it.
