### ISSUE TITLE
Resource Sensor Global Oddness,

### ISSUE THREAD

**Issue by Caseyckk** [Berkays/OniMods#4]
TLDR; Resource Sensor Global only reads values of current planet player is viewing regardless of actual location of sensor.

Global seems a bit finicky in that it only looks at the planet the player is currently viewing. So my sensor on planet 2 is reading food. When I am viewing planet 2 it turns green cause I'm low food. But if I go back to planet 1 it appears to turn off again. Pausing and going back to view planet 2 the counter shows the value for how much food is on planet 1 instead of 2.

**Comment by Berkays** [comment]
Thanks. Released 1.0.2 that fixes this.
